import math
import numpy as np
from rocketpy.mathutils.vector_matrix import Matrix, Vector
from rocketpy.prints.wire_prints import _WirePrints
from rocketpy.plots.wire_plots import _WirePlots




class Wire():
    '''
    Models the physical characteristics and magnetic field generated by an
    electric wire.

    Calculates the magnetic field generated by a current-carrying straight wire
    at specific spatial positions. Supports both continuous communication wires and
    event-based ignition wires (motor ignition, parachute deployment).

    Attributes: 
    -----------------
    wire_current : float, int
        Intensity of the current through the wire in A

    magnetic_field : dict
        Dictionary of all the magnetic fields calculated, 
        the key is the position vector of the point relative
        to the cso, and the value is the magnetic field due to
        the wire at that point as a list in T. 

    wire_length : float
        Length of the wire in m. 

    wire_type : str
        Type of wire, it can either be ignition or communications

    ignition_wire_function : str
        Sub-type of the wire, when it is an ignition wire
        because it is a HIL wire it can be:
        'parachute' or 'motor_ignition
    
    parachute_name : str
        Name of the parachute to which it is attached the wire
        in the case ignition_wire_function is parachute
    
    name : str, optional
        Name of the wire. Default is 'wire'
    
    '''
    def __init__(
        self,
        current: float | int,
        wire_type: str,
        ignition_wire_function: str | None = None,
        lead_ignition_time: float = 0,
        extra_ignition_time: float = 0,
        parachute_name: str | None = None, 
        name: str = 'wire'
    ):
        '''
        current : float, int, list
            Intensity of the current through the communication wires to calculate 
            the magnetic distortion experienced by the sensor due to activation signals
            in Amperes (A). Default is 1 A. The current goes from the first to the second
            edge defined in add_wire
        
        wire_type : str
            type of wire.
            If 'communications', the wire will be consider to
            have only information communicated from one component to 
            another, thus they will have a constatn effect on 
            the magnetic field. If 'ignition', the wire is considered
            to have flow of current only when there is an ignition.

        ignition_wire_function : str, mandatory if type is ingition
            type of ingnition wire. This parameter must be a string, for a solid rocket
            the only ignitions are the parachutes and the motor at the beggining 
            of the flight. In this case, the valid arguments are 'motor_ignition'
            'hybrid_motor_ignition' or 'liquid_motor_ignition'
            or 'parachute_ignitions'. Default is None. 

        extra_ignition_time : float, optional
            is 'parachute_ignition'. 
            Time after the ignition, in which the ignition signal is 
            wanted to be sent. Default is 0

        lead_ignition_time : float, optional
            Time before the ignition in which the ignition signal 
            is considered to be sent, thus magnetic distortion could be applied. 
            Default is 0

        parachute_name : str, mandatory when it is an ignition wire whose function is parachute 
            In the case ignition_wire_function is parachute: 
                Name of the parachtue in whose deployment we want the wire to have
                charge flow, it must be the same as the name assigned for the parachute
                The magnetic disturbance will ocurr during the selected parachute 
                ejection, simulating the signal sent by the avionics. The ejection 
                conditions will be taken from the parachute definition.

        '''
       
        # define current of the wire
        if not isinstance(current, (float, int)):
            raise ValueError('The current through the wire must be a float or int') 
        else: 
            self.current = current

        # define the lead and extra time
        if isinstance(extra_ignition_time,(float, int)):
            if extra_ignition_time < 0:
                raise ValueError('The extra ignition time must be greater than 0')
            else:
                self.extra_ignition_time = extra_ignition_time
        else:
            raise ValueError('The extra ignition time must be a float') 
        
        # define the lead and extra time
        if isinstance(lead_ignition_time,(float, int)):
            if lead_ignition_time < 0:
                raise ValueError('The lead ignition time must be greater than 0')
            else:
                self.lead_ignition_time = lead_ignition_time
        else:
            raise ValueError('The lead ignition time must be a float') 
        

        # definition of the type of wire
        if isinstance(wire_type, str):
            if wire_type == 'communications':
                self.wire_type = 'communications'
                self.ignition_wire_function = None                
            elif wire_type == 'ignition':
                self.wire_type = 'ignition'
                if ignition_wire_function == None:
                    raise ValueError('The ignition type is compulsory when it is an ignition wire')
                elif isinstance(ignition_wire_function, str):
                    if ignition_wire_function.lower() == 'parachute_ignition':
                        self.ignition_wire_function = 'parachute_ignition'
                        if parachute_name == None:
                            raise ValueError('The name of the parachute is compulsory if the ignition_wire_function is parachute')
                        elif not isinstance(parachute_name, str):
                            raise ValueError('The name of the parachute must be a string')
                        else: 
                            self.parachute_name = parachute_name
                    else: 
                        self.ignition_wire_function = ignition_wire_function
                else: 
                    raise ValueError('The type of ignition wire must be a str')
            else:
                raise ValueError('The type must be an ignition or communication')
        else: 
            raise ValueError('The type must be a string')

        if isinstance(name, str):
            self.name = name
        else: 
            raise ValueError('The name must be a str')
        
        self._magnetic_field = {}
        self.magnetic_field = {}
        self._wire_edges_from_cso = None
        self.wire_length = 0

        # prints and plots
        self.prints = _WirePrints(self)
        self.plots = None
    

    def measure_magnetic_field(self, position_vector: list | tuple | Vector) -> None: 
        '''
        This function measures the magnetic field on a given position_vector
        based on the position of the edges of the wire. the magnetic field is
        calculated assuming that the wire is straight. 

        Parameters:
        --------

        position_vector: list, tuple or Vector
            position vector of the point in which the magnetic field
            is going to be measured relative to the coordiante system origin choosen
            by the user. 

        Returns:
        ---------
            None
        '''
        # definition of the required values
        r1 = self._wire_edges_from_cso[0]  # m
        r2 = self._wire_edges_from_cso[1]  # m

        if len(position_vector) == 3:
            if isinstance(position_vector, (list, tuple)):
                r_V = Vector(position_vector)  # m
                r_t   = tuple(position_vector)    # m 
            elif isinstance(position_vector, Vector):
                r_V = position_vector          # m
                r_t   = tuple(position_vector) # m
            else: 
                raise ValueError('The only accepted parameters are list, tuple or Vector')
        else:
            raise ValueError('The length of the position vector must be 3, x,y,z')    
        
        l = r2 - r1 #m
        self.wire_length = abs(l) # m

        r1_V =  r_V - r1 # m
        r2_V =  r_V - r2 # m

        cross_r1_r2 = (r1_V ^ r2_V)
        cross_norm_r1_r2 = abs(cross_r1_r2)

        dot_term = l @ (r1_V.unit_vector - r2_V.unit_vector)

        if cross_norm_r1_r2 < 1e-12: #along the same line, cross product is zero -> magnetic field is 0
            b_V = Vector([0,0,0]) 
        else:
            b_V = (1e-7 * self.current) * (cross_r1_r2 / (cross_norm_r1_r2 ** 2)) * dot_term # T
       
        self.magnetic_field[r_t]  = list(b_V)
        self._magnetic_field[r_t] = b_V

    
    def define_magnetic_field(
        self, position_vector: list | tuple | Vector, 
        magnetic_field: float | int | list | tuple | Vector
    ) -> None: 
        '''
        This function allows to defined the magnetic field at a certain point
        and this will the value used for the calculations. 

        Parameters:
        ------------
        position_vector: list, tuple
            position vector of the point where the magnetic field is
            defined

        magnetic_field: int, float, list, tuple
            Magnetic influence on the position given by position_vector in T: 

            - If a float, it assumes that the wire genertes the same magnetic field
              on each axis, with the given value. 

            - If a tuple or list, it assumes that the wire genertes the given magnetic
              field. 

        Returns:
        ---------
            None
        '''
        if isinstance(position_vector, (tuple, list, Vector)):
            if len(position_vector) == 3:
                position_vector_t = tuple(position_vector)
                if isinstance(magnetic_field, (float, int)):
                    m_field = [magnetic_field, magnetic_field, magnetic_field]
                    self._magnetic_field[position_vector_t] = Vector(m_field)
                    self.magnetic_field[position_vector_t] = m_field
                elif isinstance(magnetic_field, (list, tuple, Vector)):
                    if len(magnetic_field) == 3: 
                        if isinstance(magnetic_field, (list, tuple)):
                            self._magnetic_field[position_vector_t] = Vector(magnetic_field)
                            self.magnetic_field[position_vector_t] = magnetic_field
                        elif isinstance(magnetic_field, Vector):
                            self._magnetic_field[position_vector_t] = magnetic_field
                            self.magnetic_field[position_vector_t] = list(magnetic_field)
                    else:
                        raise ValueError('If a list, tuple or Vector is passed, it must have one value for each axis. Therefore, it must have length 3')
            else:
                raise ValueError('The position_vector must be a list, tuple or Vector with 3 elements')
        else:
            raise ValueError('The position_vector must be a list, tuple or Vector')
        

    def _set_wire_edges_from_cso(self, _wire_edges_from_cso: list | tuple | Vector [Vector, Vector]) -> None: 
        '''
        Save as an attribute the position of the wire edges from the coordiante system
        origin, chosen by the user.
        
        Parameters:
        ------------
        wire_edges_from_cso: list/tuple/Vector [Vector, Vector]
            containing the edges position relative to the the coordiante system
            origin as a Vector instances.  

        Returns:
        --------
            None
        '''
        self._wire_edges_from_cso = _wire_edges_from_cso


    def _rocket_belonging(self, rocket):
        '''
        This funciton is used to initializate _WirePlot class by
        passing the rocket instance to which it belogns

        Parameter:
        ----------
        rocket: Rocket
            rocket instance to which it belongs
        
        Returns: 
        -------
        None
        '''
        self.plots = _WirePlots(self, rocket)



    def info(self):
        '''
        Print a summary of the information stored in the plate object

        Returns
        -------
        None
        '''
        self.prints.all()


    def all_info(self):
        '''
        Prints out all data and graphs available about the Plate.

        Returns
        -------
        None
        '''
        self.plots.all()
        self.prints.all()


    @classmethod
    def from_dict(cls, data: dict) -> "Wire":
        '''
        Creates an instance of Wire from a dictionary object, data. 
        Data is a dictionary that must contain the same keys as the initialization
        parameter of the Wire class. In the case some parameter is not 
        defined, the default value matches the default intializaiton of the constructor
        Parameters:
        ----------
        data : dict
            Dictionary containing wire constructor attributes.
            
        Returns:
        ---------
            Wire object instance with the provided attributes
        '''
        return cls(
            # Mandatory Parameters 
            current = data['current'],
            wire_type = data['wire_type'],
            
            # Optional Parameters 
            ignition_wire_function = data.get('ignition_wire_function', None),
            lead_ignition_time = data.get('lead_ignition_time', 0),
            extra_ignition_time = data.get('extra_ignition_time', 0),
            parachute_name = data.get('parachute_name', None)
        )