import math as m
import warnings

from rocketpy.mathutils.vector_matrix import Vector
from rocketpy.plots.wire_plots import _WirePlots
from rocketpy.prints.wire_prints import _WirePrints


class Wire:
    """
    Models the physical characteristics and magnetic field generated by an
    electric wire.

    Calculates the magnetic field generated by a current-carrying straight wire
    at specific spatial positions. Supports both continuous communication wires and
    event-based ignition wires (motor ignition, parachute deployment).

    Attributes
    ----------
    Wire.wire_current : float, int
        Intensity of the current through the wire in A
    Wire.magnetic_field : dict
        Dictionary of all the magnetic fields calculated,
        the key is the position vector of the point relative
        to the body axis coordinate system,
        and the value is the magnetic field due to the wire
        at that point as a list in T.
    Wire.wire_length : float
        Length of the wire in m.
    Wire.wire_type : str
        Type of wire, it can either be ignition or communications
    Wire.ignition_wire_function : str
        Sub-type of the wire, when it is an ignition wire
        because it is a HIL wire it can be:
        'parachute_deployment' or 'motor_ignition
    Wire.name: str
        Name of the wire.

    """

    def __init__(
        self,
        current: float | int,
        wire_type: str,
        ignition_wire_function: str | None = None,
        extra_ignition_time: float = 0,
        name: str = "wire",
    ):
        """
        Initializes the Wire class.

        Parameters
        ----------
        current : float, int, list
            Intensity of the current through the communication wires to calculate
            the magnetic distortion experienced by the sensor due to activation signals
            in Amperes (A). Default is 1 A. The current goes from the first to the second
            edge defined in add_wire.
        wire_type : str
            type of wire.
            If 'communications', the wire will be consider to
            have only information communicated from one component to
            another, thus they will have a constatn effect on
            the magnetic field. If 'ignition', the wire is considered
            to have flow of current only when there is an ignition.
        ignition_wire_function : str, mandatory if type is ingition
            type of ingnition wire. This parameter must be a string, for a solid rocket
            the only ignitions are the parachutes and the motor at the beggining
            of the flight. In this case, the valid arguments are 'motor_ignition'
            or 'parachute_deployments'. Default is None.
        extra_ignition_time : float, optional
            is 'parachute_deployment'.
            Time after the ignition, in which the ignition signal is
            wanted to be sent. Default is 0.
        name : str, optional
            Name of the wire. Default is 'wire'

        """
        self.validate_parameters(
            current, extra_ignition_time, wire_type, ignition_wire_function
        )
        self._magnetic_field = {}
        self.magnetic_field = {}
        self._wire_edges_bacs = []
        self.wire_length = 0
        self.parachute_name = None
        self.name = name

        # prints and plots
        self.prints = _WirePrints(self)
        self.plots = None

    def validate_parameters(
        self, current, extra_ignition_time, wire_type, ignition_wire_function
    ):
        """
        Check and defines several attributes of wire.
        """
        self._validate_wire_type(wire_type, ignition_wire_function)
        self._validate_numbers(current, extra_ignition_time)

    def _validate_wire_type(self, wire_type, ignition_wire_function):
        """
        Check and defines the attributes related to the type of wire
        """
        if isinstance(wire_type, str):
            if wire_type == "communications":
                self.wire_type = "communications"
                self.ignition_wire_function = None
            elif wire_type == "ignition":
                self.wire_type = "ignition"
                if ignition_wire_function is None:
                    raise ValueError(
                        "The ignition type is compulsory when it is an ignition wire"
                    )
                elif not isinstance(ignition_wire_function, str):
                    raise ValueError("Ignition wire function must be a string")
                else:
                    self.ignition_wire_function = ignition_wire_function
        else:
            raise ValueError("Wire type must be a string")

    def _validate_numbers(self, current, extra_ignition_time):
        if not isinstance(current, (float, int)):
            raise ValueError("Current must be a float or int. ")
        else:
            self.current = current
        if not isinstance(extra_ignition_time, (float, int)):
            raise ValueError("extra_ignition_time must be a float or int.")
        else:
            if extra_ignition_time < 0:
                raise ValueError("extra_ignition_time must be greater or equal than 0.")
            else:
                self.extra_ignition_time = extra_ignition_time

    def measure_magnetic_field(self, position_vector: list | tuple | Vector) -> None:
        """
        Measures the magnetic field on a given position_vector based on the position
        of the edges of the wire. The magnetic field is calculated assuming that the
        wire is straight.

        Parameters
        ----------
        position_vector: list, tuple or Vector
            position vector of the point in which the magnetic field
            is going to be measured in the user defined coordinate system

        Returns
        -------
        None
        """
        r1 = self._wire_edges_bacs[0]  # starting edge
        r2 = self._wire_edges_bacs[1]  # final end

        r_v = Vector(position_vector)
        r_t = tuple(position_vector)

        l = r2 - r1  # Vector along the wire pointing in direction of current
        self.wire_length = abs(l)

        if self.wire_length < 1e-12:
            self.magnetic_field[r_t] = [0.0, 0.0, 0.0]
            self._magnetic_field[r_t] = Vector([0.0, 0.0, 0.0])
            return

        r1_v = r_v - r1
        r2_v = r_v - r2

        cross_l_r1 = l ^ r1_v
        cross_norm = abs(cross_l_r1)

        if cross_norm < 1e-12:
            b_v = Vector([0, 0, 0])
            warnings.warn(
                "The wire is along the same line as the position vector, thus the magnetic field is 0",
                UserWarning,
            )
        else:
            l_unit = l / self.wire_length
            cos_theta1 = l_unit @ r1_v.unit_vector
            cos_theta2 = l_unit @ r2_v.unit_vector

            b_v = (
                (1e-7 * self.current)
                * (cross_l_r1 / (cross_norm**2))
                * (cos_theta1 - cos_theta2)
                * self.wire_length
            )

        self.magnetic_field[r_t] = list(b_v)
        self._magnetic_field[r_t] = b_v

    def define_magnetic_field(
        self,
        position_vector: list | tuple | Vector,
        magnetic_field: float | int | list | tuple | Vector,
    ) -> None:
        """
        Allows to define the magnetic field at a certain point and this will the
        value used for the calculations.

        Parameters
        ----------
        position_vector: list, tuple
            position vector of the point where the magnetic field is
            defined in the body axis coordinate system.
        magnetic_field: int, float, list, tuple
            Magnetic influence on the position given by position_vector in T:

            - If a float, it assumes that the wire genertes the same magnetic field
              on each axis, with the given value.

            - If a tuple, list or Vector, it assumes that the wire genertes the given magnetic
              field.
        Returns
        -------
        None
        """
        position_vector_t = tuple(position_vector)
        if isinstance(magnetic_field, (float, int)):
            magnetic_field = [magnetic_field, magnetic_field, magnetic_field]
        self._magnetic_field[position_vector_t] = Vector(magnetic_field)
        self.magnetic_field[position_vector_t] = magnetic_field

    def _set_wire_edges_from_bacs(
        self, rocket, _wire_edges_from_user_coordinate_system: list[Vector, Vector]
    ) -> None:
        """
        Save as an attribute the position of the wire edges in the body axis
        coordinate system from the edges given as a vector in the user
        defined coordinate system

        Parameters
        ----------
        _wire_edges_from_user_coordinate_system: list[Vector, Vector]
            Containing the edges position relative to the the user defined
            coordinate system as a Vector instances.
        rocket : Rocket
            Rocket instance to which it belongs.

        Returns
        -------
        None
        """

        self._wire_edges_bacs = []
        cdm_user_frame = Vector([0, 0, rocket.center_of_dry_mass_position])
        for edge_from_user in _wire_edges_from_user_coordinate_system:
            self.check_entry_dimensions(edge_from_user, rocket)
            edge_from_cdm_user_frame = edge_from_user - cdm_user_frame
            if rocket._csys == -1:  # nose to tail
                edge_position_bacs_frame = Vector(
                    [
                        -edge_from_cdm_user_frame[0],
                        edge_from_cdm_user_frame[1],
                        -edge_from_cdm_user_frame[2],
                    ]
                )
            else:  # tail to nose
                edge_position_bacs_frame = edge_from_cdm_user_frame
            self._wire_edges_bacs.append(edge_position_bacs_frame)

    def _rocket_belonging(self, rocket) -> None:
        """
        Initializate _WirePlot class with the rocket instance to which it belogns.

        Parameter
        ---------
        rocket : Rocket
            Rocket instance to which it belongs.

        Returns
        -------
        None
        """
        self.plots = _WirePlots(self, rocket)

    def info(self) -> None:
        """
        Print a summary of the information stored in the plate object.

        Returns
        -------
        None
        """
        self.prints.all()

    def all_info(self) -> None:
        """
        Prints out all data and graphs available about the Plate.

        Returns
        -------
        None
        """
        self.plots.all()
        self.prints.all()

    def check_entry_dimensions(self, pt, rocket) -> None:
        """
        Check whether the edges are inside the rocket.

        Parameters
        ----------
        edge: list
            Edge given as a list of three components in the usc frame.
        rocket: Rocket
            Rocket to which the plate belongs.

        Returns
        -------
        None
        """
        if not rocket.z_bounds_check(pt[2], frame="ucs")[0]:
            raise ValueError(
                f"The z component: {pt[2]} of {pt} is outside the rocket range."
            )

        if m.hypot(pt[0], pt[1]) > rocket.general_radius(pt[2], frame="ucs"):
            raise ValueError(f"Point {pt} is outside the rocket radius at z={pt[2]}.")

    @classmethod
    def from_dict(cls, data: dict) -> "Wire":
        """
        Creates an instance of Wire from a dictionary object, data.
        Data is a dictionary that must contain the same keys as the initialization
        parameter of the Wire class. In the case some parameter is not
        defined, the default value matches the default intializaiton of the constructor.

        Parameters
        ----------
        data : dict
            Dictionary containing wire constructor attributes.

        Returns
        -------
            Wire object instance with the provided attributes
        """
        return cls(
            # Mandatory Parameters
            current=data["current"],
            wire_type=data["wire_type"],
            # Optional Parameters
            ignition_wire_function=data.get("ignition_wire_function", None),
            extra_ignition_time=data.get("extra_ignition_time", 0),
        )
