import math as m
import warnings

from rocketpy.mathutils.vector_matrix import Vector
from rocketpy.plots.wire_plots import _WirePlots
from rocketpy.prints.wire_prints import _WirePrints


class Wire:
    """Models the physical characteristics and magnetic field generated by an
    electric wire.

    Calculates the magnetic field generated by a current-carrying straight wire
    at specific spatial positions. Supports both continuous communication wires and
    event-based ignition wires (motor ignition, parachute deployment).

    Attributes
    ----------
    Wire.current : float, int
        Intensity of the current through the wire in Amperes (A).
    Wire.magnetic_field : dict
        Dictionary of all calculated magnetic fields. Keys are the position
        vector tuples of the point relative to the body axis coordinate system (BACS),
        and values are the magnetic field vectors due to the wire at that point in Tesla (T).
    Wire.wire_length : float
        Length of the wire in meters (m).
    Wire.wire_type : str
        Type of wire; can be either 'communications' or 'ignition'.
    Wire.ignition_wire_function : str or None
        Sub-type of the wire when wire_type is 'ignition'. Can be:
        'parachute_deployment' or 'motor_ignition'.
    Wire.name : str
        Name of the wire.
    """

    def __init__(
        self,
        current: float | int,
        wire_type: str,
        ignition_wire_function: str | None = None,
        extra_ignition_time: float = 0,
        name: str = "wire",
    ):
        """Initializes the Wire class.

        Parameters
        ----------
        current : float, int
            Intensity of the current through the wire in Amperes (A).
            Conventional current flows from the first to the second edge defined
            in add_wire.
        wire_type : str
            Type of wire:

            - If 'communications', the wire represents continuous data/power
              flow, contributing a constant magnetic field.
            - If 'ignition', current flows only during active ignition/deployment events.
        ignition_wire_function : str, optional
            Function of ignition wire (mandatory if wire_type is 'ignition').
            Valid options are 'motor_ignition' or 'parachute_deployment'.
            Default is None.
        extra_ignition_time : float, optional
            Additional duration in seconds (s) for which the ignition signal remains
            active after the event trigger. Default is 0.
        name : str, optional
            Name of the wire. Default is 'wire'.
        """
        self._validate_parameters(
            current, extra_ignition_time, wire_type, ignition_wire_function
        )
        self._magnetic_field = {}
        self.magnetic_field = {}
        self._wire_edges_bacs = []
        self.wire_length = 0
        self.parachute_name = None
        self.name = name

        # prints and plots
        self.prints = _WirePrints(self)
        self.plots = None

    def _validate_parameters(
        self, current, extra_ignition_time, wire_type, ignition_wire_function
    ):
        """
        Check and defines several attributes of wire.
        """
        self._validate_wire_type(wire_type, ignition_wire_function)
        self._validate_numbers(current, extra_ignition_time)

    def _validate_wire_type(self, wire_type, ignition_wire_function):
        """
        Check and defines the attributes related to the type of wire.
        """
        if isinstance(wire_type, str):
            if wire_type == "communications":
                self.wire_type = "communications"
                self.ignition_wire_function = None
            elif wire_type == "ignition":
                self.wire_type = "ignition"
                if ignition_wire_function is None:
                    raise ValueError(
                        "The ignition type is compulsory when it is an ignition wire."
                    )
                elif not isinstance(ignition_wire_function, str):
                    raise ValueError("Ignition wire function must be a string.")
                else:
                    self.ignition_wire_function = ignition_wire_function
        else:
            raise ValueError("Wire type must be a string.")

    def _validate_numbers(self, current, extra_ignition_time):
        if not isinstance(current, (float, int)):
            raise ValueError("Current must be a float or int.")
        else:
            self.current = current
        if not isinstance(extra_ignition_time, (float, int)):
            raise ValueError("extra_ignition_time must be a float or int.")
        else:
            if extra_ignition_time < 0:
                raise ValueError("extra_ignition_time must be greater or equal than 0.")
            else:
                self.extra_ignition_time = extra_ignition_time

    def measure_magnetic_field(self, position_vector: list | tuple | Vector) -> None:
        """
        Measures the magnetic field on a given position_vector based on the position
        of the edges of the wire. The magnetic field is calculated assuming that the
        wire is straight.

        Parameters
        ----------
        position_vector: list, tuple or Vector
            position vector of the point in which the magnetic field
            is going to be measured in the user defined coordinate system.

        Returns
        -------
        None
        """
        r1 = self._wire_edges_bacs[0]  # starting edge
        r2 = self._wire_edges_bacs[1]  # final end

        r_v = Vector(position_vector)
        r_t = tuple(position_vector)

        l = r2 - r1  # Vector along the wire pointing in direction of current
        self.wire_length = abs(l)

        if self.wire_length < 1e-12:
            self.magnetic_field[r_t] = [0.0, 0.0, 0.0]
            self._magnetic_field[r_t] = Vector([0.0, 0.0, 0.0])
            return

        r1_v = r_v - r1
        r2_v = r_v - r2

        cross_l_r1 = l ^ r1_v
        cross_norm = abs(cross_l_r1)

        if cross_norm < 1e-12:
            b_v = Vector([0, 0, 0])
            warnings.warn(
                "The wire is along the same line as the position vector, thus the magnetic field is 0.",
                UserWarning,
            )
        else:
            l_unit = l / self.wire_length
            cos_theta1 = l_unit @ r1_v.unit_vector
            cos_theta2 = l_unit @ r2_v.unit_vector

            b_v = (
                (1e-7 * self.current)
                * (cross_l_r1 / (cross_norm**2))
                * (cos_theta1 - cos_theta2)
                * self.wire_length
            )

        self.magnetic_field[r_t] = list(b_v)
        self._magnetic_field[r_t] = b_v

    def define_magnetic_field(
        self,
        position_vector: list | tuple | Vector,
        magnetic_field: float | int | list | tuple | Vector,
    ) -> None:
        """
        Allows to define the magnetic field at a certain point and this will the
        value used for the calculations.

        Parameters
        ----------
        position_vector: list, tuple
            position vector of the point where the magnetic field is
            defined in the body axis coordinate system.
        magnetic_field: int, float, list, tuple
            Magnetic influence on the position given by position_vector in T:

            - If a float, it assumes that the wire generates the same magnetic field
              on each axis, with the given value.

            - If a tuple, list or Vector, it assumes that the wire generates the given magnetic
              field.
        Returns
        -------
        None
        """
        position_vector_t = tuple(position_vector)
        if isinstance(magnetic_field, (float, int)):
            magnetic_field = [magnetic_field, magnetic_field, magnetic_field]
        self._magnetic_field[position_vector_t] = Vector(magnetic_field)
        self.magnetic_field[position_vector_t] = magnetic_field

    def _set_wire_edges_from_bacs(
        self, rocket, _wire_edges_from_user_coordinate_system: list[Vector, Vector]
    ) -> None:
        """
        Save as an attribute the position of the wire edges in the body axis
        coordinate system from the edges given as a vector in the user
        defined coordinate system.

        Parameters
        ----------
        _wire_edges_from_user_coordinate_system: list[Vector, Vector]
            Containing the edges position relative to the the user defined
            coordinate system as a Vector instances.
        rocket : Rocket
            Rocket instance to which it belongs.

        Returns
        -------
        None
        """

        self._wire_edges_bacs = []
        cdm_user_frame = Vector([0, 0, rocket.center_of_dry_mass_position])
        for edge_from_user in _wire_edges_from_user_coordinate_system:
            self._check_entry_dimensions(edge_from_user, rocket)
            edge_from_cdm_user_frame = edge_from_user - cdm_user_frame
            if rocket._csys == -1:  # nose to tail
                edge_position_bacs_frame = Vector(
                    [
                        -edge_from_cdm_user_frame[0],
                        edge_from_cdm_user_frame[1],
                        -edge_from_cdm_user_frame[2],
                    ]
                )
            else:  # tail to nose
                edge_position_bacs_frame = edge_from_cdm_user_frame
            self._wire_edges_bacs.append(edge_position_bacs_frame)

    def _rocket_belonging(self, rocket) -> None:
        """Initialize _WirePlots class with the rocket instance to which it belongs.

        Parameters
        ----------
        rocket : Rocket
            Rocket instance to which it belongs.

        Returns
        -------
        None
        """
        self.plots = _WirePlots(self, rocket)

    def info(self) -> None:
        """Print a summary of the information stored in the wire object.

        Returns
        -------
        None
        """
        self.prints.all()

    def all_info(self) -> None:
        """Prints out all data and graphs available about the Wire.

        Returns
        -------
        None
        """
        self.plots.all()
        self.prints.all()

    def _check_entry_dimensions(self, pt, rocket) -> None:
        """Check whether the edges are inside the rocket.

        Parameters
        ----------
        pt : list, Vector
            Edge coordinates [x, y, z] in the UCS frame in meters (m).
        rocket : Rocket
            Rocket to which the wire belongs.

        Returns
        -------
        None
        """
        if not rocket.z_bounds_check(pt[2], frame="ucs")[0]:
            raise ValueError(
                f"The z component: {pt[2]} of {pt} is outside the rocket range."
            )

        if m.hypot(pt[0], pt[1]) > rocket.general_radius(pt[2], frame="ucs"):
            raise ValueError(f"Point {pt} is outside the rocket radius at z={pt[2]}.")

    @classmethod
    def from_dict(cls, data: dict) -> "Wire":
        """Creates an instance of Wire from a dictionary object, data.
        Data is a dictionary that must contain the same keys as the initialization
        parameters of the Wire class. In case some parameter is not defined,
        the default value matches the default initialization of the constructor.

        Parameters
        ----------
        data : dict
            Dictionary containing wire constructor attributes.

        Returns
        -------
        wire: Wire
            Wire object instance with the provided attributes.
        """
        return cls(
            # Mandatory Parameters
            current=data["current"],
            wire_type=data["wire_type"],
            # Optional Parameters
            ignition_wire_function=data.get("ignition_wire_function", None),
            extra_ignition_time=data.get("extra_ignition_time", 0),
        )
